services:
  nginx:
    image: nginx:1.25-alpine
    container_name: bomberos_nginx
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - bomberos_net

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: bomberos_app
    volumes:
      - ./src:/var/www/html
    env_file:
      - .env.docker
    depends_on:
      - postgres
      - redis
    networks:
      - bomberos_net

  mailpit:
    image: axllent/mailpit:latest
    container_name: bomberos_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"   # UI web
      - "1025:1025"   # SMTP
    networks:
      - bomberos_net

  vite:
    image: node:20-alpine
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    command: sh -lc "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    networks:
      - bomberos_net
    depends_on:
      - app
  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: bomberos_queue
    working_dir: /var/www/html
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - ./src:/var/www/html
    env_file:
      - .env.docker
    depends_on:
      - app
      - redis
    networks:
      - bomberos_net

  postgres:
    image: postgres:16-alpine
    container_name: bomberos_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: bomberos
      POSTGRES_USER: dilan_dam
      POSTGRES_PASSWORD: N3w_S3cur3_P@ssw0rd_2026!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bomberos_net

  redis:
    image: redis:7-alpine
    container_name: bomberos_redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - bomberos_net

networks:
  bomberos_net:
    driver: bridge

volumes:
  postgres_data:
